name: massive_pixel_recruitment_task
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.3
  flutter_bloc: ^8.1.5
  http: ^1.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^9.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.2.4
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
